# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0a2290291bab9e42e1bdb1d6a3817c24d0498c5f21bb38e466e4f84dda0daf86c72c79a1425c04ca23d95c5bc48886180e2d65445ed2f1e7ffac9b763a32e9d1

test:
  secret_key_base: 4796c651e5ce4d31f60828c3e6bf78476d13504e32676573ab0d7022c0e721d4b2cdaf227e097d276ca288268b73c90569e1a8877e0f7c5a6453d810561efb6c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
